baseURL = "https://tsu-nera.github.io/keido/"
title = "Keido"
theme = "hugo-geekdoc"

pluralizeListTitles = false

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/keido/404.html"

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
   tag = "tags"

[params]
   type = "notes"
   geekdocMenuBundle: true
