baseURL: "https://tsu-nera.github.io/keido/"

countryCode: ja
languageCode: ja
HasCJKLanguage: true

title: Keido
theme: even

googleAnalytics:

refLinksErrorLevel: "WARNING"
refLinksNotFoundURL: /keido/404.html

